### ISSUE TITLE
Rewrite the library game detection 

### ISSUE THREAD

**Issue by IroAlexis** [IroAlexis/lunion#2]
# ToDo List :
- [x] Detects only directory
- [x] Better code lisiblity, specially for memory release (need implement a release function)
- [ ] Use the user path (actually use my path :frog:)
- [ ] Detects the installation type (Linux or Wine)
